services:
    scriptkill-ai-backend:
      build:
        context: .
      restart: unless-stopped
      container_name: scriptkill-ai-backend
      environment:
      - MONGODB_URL=mongodb://seo_ai:14f118d5f470da591218e9a5@mongodb:27017
      ports:
        - 18000:8000
      networks:
        - shared_network
      env_file:
        - .env
      volumes:
        - ./:/app

networks:
  shared_network:
    external: true